### ISSUE TITLE
Starbridge listener panics on receiving StartTLS command

### ISSUE THREAD

**Issue by hwh33** [OperatorFoundation/Starbridge-go#1]
As stated in the title, the Starbridge listener panics when an SMTP client connects and sends the StartTLS command.  This behavior is non-deterministic, occurring roughly 50% of the time.  Here is a self-contained example:
```
package main

import (
	"crypto/tls"
	"encoding/base64"
	"fmt"
	"net"
	"net/smtp"

	"github.com/OperatorFoundation/Starbridge-go/Starbridge/v3"
)

func main() {
	_, priv, err := Starbridge.GenerateKeys()
	if err != nil {
		panic(err)
	}

	serverConfig := Starbridge.ServerConfig{
		ServerAddress:    "127.0.0.1:2525",
		ServerPrivateKey: *priv,
		Transport:        "Starbridge",
	}

	go func() {
		if err := listenAndServe(serverConfig); err != nil {
			fmt.Println("serve error:", err)
		}
	}()

	c, err := smtp.Dial("127.0.0.1:2525")
	if err != nil {
		panic(err)
	}
	defer c.Close()

	if err := c.StartTLS(&tls.Config{InsecureSkipVerify: true}); err != nil {
		panic(err)
	}
}

func listenAndServe(serverConfig Starbridge.ServerConfig) error {
	l, err := serverConfig.Listen()
	if err != nil {
		panic(err)
	}
	defer l.Close()

	acceptErr := make(chan error)
	go func() {
		for {
			conn, err := l.Accept()
			if err != nil {
				acceptErr <- err
				return
			}

			go func(c net.Conn) {
				defer c.Close()

				buf := make([]byte, 1024)
				n, err := conn.Read(buf)
				if err != nil {
					fmt.Println("read error:", err)
					return
				}

				fmt.Println("from client:", base64.StdEncoding.EncodeToString(buf[:n]))
			}(conn)
		}
	}()

	return <-acceptErr
}
```

We are seeing this behavior in the wild as our proxy servers appear to be getting hit with SMTP probes.  The Starbridge listener should be resilient to such probes.  Ideally, the server would respond with something meaningful.

Of course, the server also wants to distinguish probes from actual clients.  In other circumvention protocols, we achieve this by optimistically attempting to decrypt the hidden signal from the client.  If we don't see such a signal, we treat the peer as a probe and respond with something which maintains the disguise.

I don't have enough knowledge of SMTP to say what the probe response should be.  Since a passive observer will see other clients connecting via StartTLS, the probe should observe a server which supports StartTLS.

**Comment by blanu** [comment]
Thank you for the report. Starbridge is meant to respond appropriately in this situation and valid Starbridge clients also issue StartTLS commands, so this is probably just a bug. I appreciate the code sample for reproducing the bug. We will investigate and patch this issue.

**Comment by consuelita** [comment]
Release v3.0.15 addresses the issue where an SMTP connection without the expected credentials was not sending the connection to the "blackhole" as expected. While this resolves this issue, we are doing further work to ensure that we are generating random responses with this sort of connection once the SMTP greeting is complete.

**Comment by hwh33** [comment]
Sounds great, thank you @consuelita!

**Comment by hwh33** [comment]
We have had Starbridge v3.0.15 deployed in production for over a month now without seeing this issue.  I believe this is resolved!
